# Generated by Django 5.1.3 on 2024-12-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_instructor_remove_course_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='like',
        ),
    ]
